### ISSUE TITLE
Auth header unnecessary quoting

### ISSUE THREAD

**Issue by Nalum** [rdegges/python-basicauth#3]
Is there any particular reason you are `quote`ing and `unquote`ing the `username` and `password` values?

As these values are being Base64 Encoded, there should be no reason to do so, unless it is a standard practice that I'm not aware of (entirely possible).

This is causing a miss-match in the header when I set the auth using Go or PHP.

```
def encode(username, password):
    """Returns an HTTP basic authentication encrypted string given a valid
    username and password.
    """
    return 'Basic ' + b64encode('%s:%s' % (quote(username), quote(password)))


def decode(encoded_str):
    ...
    return unquote(username), unquote(password)
```

**Comment by bugov** [comment]
Maybe because it quotes ':' in login name and password. Just guessing.

```
>>> from six.moves.urllib.parse import quote
>>> quote(':')
'%3A'
```
