### ISSUE TITLE
Please distribute a source gz on pypi

### ISSUE THREAD

**Issue by joshfriend** [rdegges/python-basicauth#9]
This is a pretty unique case where this is useful. I'm building an embedded linux image using Yocto and it is rather difficult to set up recipes for python packages that use wheels, whereas sdist is pretty easy to use.

I got around the issue by just bundling the _one file_ from this package inside my own app because that was just easier.

The solution for this issue is to just add `sdist` to your `setup.py upload` command, e.g:

```
python setup.py sdist bdist_wheel upload
```

**Comment by kynan** [comment]
@rdegges Please uploaded a source distribution. This is blocking `basicauth` from being packaged for conda-forge also

**Comment by kynan** [comment]
But please *don't* use `python setup.py upload`. [Use twine instead](https://packaging.python.org/en/latest/tutorials/packaging-projects/#generating-distribution-archives) :)

**Comment by rdegges** [comment]
Done! Sorry this took forever, but I finished modernizing the package in a number of ways and just released version 1.0.0 to [PyPI](https://pypi.org/project/basicauth/). You can check out the release notes [here](https://github.com/rdegges/python-basicauth/releases/tag/1.0.0).

<333

**Comment by kynan** [comment]
Perfect, thank you so much @rdegges !
